### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by mafe** [mikkosyrja/speedcrunch-android#1]
I know speedcrunch on Windows and I am interested in using it on Android, too.
Do you have a guide that covers the building process for an Android-APK-file and share it?

**Comment by mikkosyrja** [comment]
Android version of SpeedCrunch is still work in progress. Qt Creator and Android Studio should be enough to compile it. I am developing it in OpenSuse Linux, but it should work in Windows also.

**Comment by mafe** [comment]
Thanks for providing the first release of this great calculator. This is already working very fine for me and is comfortable to use as I knew it already from the desktop versions.

**Comment by spmp** [comment]
Can you provide more details for non-Android devs, would love to have speedcrunch on my phone 8)

**Comment by mikkosyrja** [comment]
Do you want to use it on Android or compile it to some other system?

**Comment by spmp** [comment]
I would like to build for Android 8)
 I understand this is a WIP so may not work perfectly ad will likely require some push and pull to get it working properly.
 Cheers

**Comment by mikkosyrja** [comment]
There is already built version in Releases page: https://github.com/mikkosyrja/speedcrunch-android/releases

Building requires Android Studio (https://developer.android.com/studio/install) and Qt (https://www.qt.io/download). After installation start Qt Creator, open android-speedcrunch.pro, configure project with Android kit, compile and deploy.

If I remember correctly, Qt Creator needs some configuration for Android SDK location. It may be easiest to start by creating simple Hello World application. When that works, SpeedCrunch compilation should also work.
