### ISSUE TITLE
Changing the color theme

### ISSUE THREAD

**Issue by avinash** [mikkosyrja/speedcrunch-android#2]
Hi,

First of all, thank you very much for having ported SpeedCrunch for Android. I'm using the latest release and I have to say that everything works great.

Can you please tell me if there's a way to customize the colors? Or, better, to use color themes like in the desktop app?

Thanks.

**Comment by mikkosyrja** [comment]
Colors are currently fixed, but I may support desktop style color schemes later.

**Comment by avinash** [comment]
Thanks. That would be great.
