### ISSUE TITLE
publish speedcrunch on fdroid

### ISSUE THREAD

**Issue by goyalyashpal** [mikkosyrja/speedcrunch-android#9]
hi

I am opening a request for packaging (rfp) for getting this app included in the FOSS app store: [f-droid](https://f-droid.org)

* If you oppose the inclusion, please comment here regarding that
* If you are neutral for the inclusion (i.e. dont oppose, but dont want to help with any process either), then no action is required. Though, mentioning that too will help clear the waters.
* if you actively support inclusion, then please participate here and at : https://gitlab.com/fdroid/rfp/-/issues/2130

thanks

**Comment by IzzySoft** [comment]
Adding another bullet-point: If you'd like to see your app directly at F-Droid (currently it's in my repo) and do still maintain it, drop a note here (or there) and I volunteer to provide you with a "starter package" for the requested [Fastlane structures](https://gitlab.com/-/snippets/1895688) via PR here to your repo.

**Comment by goyalyashpal** [comment]
closing due to no response, feel free to reopen whenever u feel it
